### ISSUE TITLE
where is the `pn` command?

### ISSUE THREAD

**Issue by sunwayforever** [baohaojun/beagrep#2]
I am trying to run beagrep under archlinux,  the error msg is `/usr/local/bin//beagrep-files: line 19: pn: command not found`, where is the `pn` command?

**Comment by baohaojun** [comment]
ahhh...

It's a script I wrote for awk: pn N = awk '{print $N}'.

Fixed.

**Comment by baohaojun** [comment]
This pn command is in my system-config project, for which beagrep is a submodule...
