### ISSUE TITLE
ag also workds faster at second times;

### ISSUE THREAD

**Issue by wsdjeg** [baohaojun/beagrep#3]
I have tested ag,also works faster at second times;
ag first time need 12s second time 0.3s
beagrep first 22s second 0.8s

**Comment by baohaojun** [comment]
Your are right, it is not fair for ag when running on some smaller projects. I will remove the comparison in the readme. Actually there is a tool quite like beagrep that's called opengrok, which provide a web interface and might be more user friendly in some user's eyes (but I myself will of course always stick to beagrep😄).

**Comment by wsdjeg** [comment]
of course, no one is more familiar with the project than you

**Comment by wsdjeg** [comment]
@baohaojun I wilk have a try with the project.and I want to create a vim plugin for it.
