### ISSUE TITLE
请问archlinux下如何编译这个项目?

### ISSUE THREAD

**Issue by wsdjeg** [baohaojun/beagrep#4]
你好, 我阅读了项目的主页,只有一个debain的编译介绍, 我希望可以在archlinux下编译这个项目,替换掉ag.
目前对搜索工具有这样的需求,
1. 自动分析 全局gitignore 和 项目 内的 gitignre
2.  -ignore + 表达式, 去除不需要的 文件, 比如 `--ignore  *.png` 去除图片
3. 包含 某个文件夹 , 比如 我的 `.gitignore` 中 有 `localtest/`,忽略的 项目下`localtest`文件夹, 我需要包含这个,以便于我检索 本地临时测试的文件.

**Comment by baohaojun** [comment]
自动分析gitignore等等是做不到的，并没有支持这个功能的计划。
