### ISSUE TITLE
原始的代码目录改名后如何快速更新索引?

### ISSUE THREAD

**Issue by sunwayforever** [baohaojun/beagrep#5]
原始的代码目录为 A, 针对 A 已经建立好索引. 后来把 A 改名为 B, 如何能快速的重新建立索引?

**Comment by baohaojun** [comment]
这个目前是没有办法快速重建索引的。beagle里用了绝对路径。所以只能重新建一遍索引了。

想要可以快速重建、甚至重用索引的话，beagrep需要做一些比较大的重构，比如不能用绝对路径，只用相对路径，目前没有精力做这块开发。
