### ISSUE TITLE
使用最新的代码无法匹配文件名？

### ISSUE THREAD

**Issue by sunwayforever** [baohaojun/beagrep#6]
Compilation started at Thu Nov  3 11:17:27

beagrep -f  -e 'heap.cc'

Compilation finished at Thu Nov  3 11:17:27

但 heap.cc 这个文件在存在的：

Compilation started at Thu Nov  3 11:18:32

beagrep  -e 'heap'
....
/media/sshfs/builder/source/whale2/art/runtime/gc/heap.cc:17:#include "heap.h"
/media/sshfs/builder/source/whale2/art/runtime/gc/heap.cc:39:#include "gc/accounting/heap_bitmap-inl.h"
/media/sshfs/builder/source/whale2/art/runtime/gc/heap.cc:61:#include "heap-inl.h"
....

和 mono 的版本有关么？ 我用的是  archlinux, mono 相关的版本是:

$> pacman -Ss mono|grep installed
extra/art-sharp 2.24.2-4 [installed]
extra/gnome-vfs-sharp 2.24.2-4 [installed]
extra/libgnome-sharp 2.24.2-4 [installed]
extra/mono 4.6.1.3-1 [installed]
extra/mono-tools 3.10-3 [installed]
extra/webkit-sharp 0.3-5 [installed]
community/terminus-font 4.40-2 [installed]

**Comment by baohaojun** [comment]
我能确定是有这个Bug，马上查一下...

**Comment by baohaojun** [comment]
Fixed.

**Comment by DigitAlchemies** [comment]
sunwayforever: 

This is regarding my Android Sensor Emulation project that was hosted by
me on Google Code under GPLv3 license at
https://code.google.com/archive/p/android-sensor-emulation/. You have
illegally copied and hosted that project in your GitHub profile at
https://github.com/sunwayforever/android-sensor-emulation
WITHOUT my permission and knowledge. This is NOT allowed. You are
violating the copyright that I have on my source code in that project.
You DON'T have permission for hosting my project as yours in your
GitHub profile. So, you MUST delete that project immediately. I have
sent you couple of emails. I didn't get any response. So, I am posting
here. If you don't delete it in couple of days from now, I will raise
a DMCA copyright violation complaint with GitHub as I have already
contacted them about this. So, I want you to immediately delete my
project hosted by you at : 
https://github.com/sunwayforever/android-sensor-emulation
And do NOT do this type of copying in future without informing the owner
of the project.

- Raghavan
