### ISSUE TITLE
ubuntu16.04上使用beagrep

### ISSUE THREAD

**Issue by cecwxf** [baohaojun/beagrep#8]
在ubuntu16.04上按照上述方法执行问题.

(1)mono-gmcs 编译工具升级为mono-xbuild或者mono-gmcs

(2)libmono-posix2.0-cil已经升级为libmono-posix4.0-cil

source code进行修改,以后就可以在ubuntu16.04上正常使用了.以后的版本也如法炮制.
diff --git a/configure.in b/configure.in
index 887d724..ea6f928 100644
--- a/configure.in
+++ b/configure.in
@@ -46,9 +46,9 @@ if test "x$MONO" = "xno"; then
AC_MSG_ERROR([You need to install the Mono runtime])
fi

-AC_PATH_PROG(MCS, gmcs, no)
+AC_PATH_PROG(MCS, mcs, no)
if test "x$MCS" = "xno"; then
- AC_MSG_ERROR([You need to install the Mono gmcs compiler])
+ AC_MSG_ERROR([You need to install the Mono mcs compiler])
fi

AC_MSG_CHECKING([for mono.pc])
diff --git a/debian/control b/debian/control
index 8dfbb39..f6ab43e 100644
--- a/debian/control
+++ b/debian/control
@@ -14,7 +14,7 @@ Build-Depends:
libgtk2.0-dev,
libmono-2.0-dev,
libmono-cil-dev,
- libmono-posix2.0-cil,
+ libmono-posix4.0-cil,
libpcre3-dev,
libsigsegv2,
libsqlite3-dev,
@@ -22,7 +22,7 @@ Build-Depends:
mime-support,
mono-devel,
monodoc-base,
- mono-gmcs,
+ mono-mcs,
pkg-config,
shared-mime-info,
tzdata
@@ -37,7 +37,7 @@ Depends: ${shlibs:Depends}, ${misc:Depends}, ${cli:Depends}, bash (>= 3.0),
libglib2.0-0,
libglib2.0-cil,
libmono-2.0-1,
- libmono-posix2.0-cil,
+ libmono-posix4.0-cil,
libmono-sqlite2.0-cil,
libsqlite3-0,
libstring-shellquote-perl,

 

compile beagrep:
set -e; autoreconf -i; ./configure; make -j4; sudo make install; echo OK

install beagrep:
apt-get install $(cat debian/control | perl -ne 'print if m/Build-Depends/..m/Standards-Version/'|grep -v -e Build-Depends:\\\|Standards-Version|perl -npe 's/,/ /g')

**Comment by baohaojun** [comment]
谢谢。

beagrep已经有一个for-ubuntu-xenial分支的，跟master分支merge一下就可以使用。
