### ISSUE TITLE
在cygwin下执行报错

### ISSUE THREAD

**Issue by zbjxb** [baohaojun/beagrep#9]
$ ./build-win.sh
: invalid optionline 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./build-win.sh: line 7: syntax error near unexpected token `$'in\r''
'/build-win.sh: line 7: `    case "$1" in

**Comment by baohaojun** [comment]
I have no idea what is this error. Have you changed the file? Seems your output is confusing. The line 2 is a very simple ``set -ex'', which is perfectly standard bash. So I'm thinking maybe your cygwin environment is buggy?

Anyway, I have stopped working on cygwin version of beagrep long time ago. If you want to try, I'd recommend you to try it on Win10+Ubuntu (which I myself have not tried, but heard is very promising).
